<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AtasIndicators</AssemblyName>
    <RootNamespace>AtasIndicators</RootNamespace>
    <Platforms>x64</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ATAS.Indicators">
      <HintPath>..\libs\ATAS.Indicators.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OFT.Rendering">
      <HintPath>..\libs\OFT.Rendering.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OFT.Core">
      <HintPath>..\libs\OFT.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
     <Reference Include="ATAS.DataFeedsCore">
      <HintPath>..\libs\ATAS.DataFeedsCore.dll</HintPath>
      </Reference>
  </ItemGroup>

</Project>
